@startuml CameraLogic
state "CameraLogic State" as Jomolith_Play_Player_Camera_State_CameraLogic_CameraState {
  state "Locked" as Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_Locked {
    state "FirstPerson" as Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_FirstPerson {
      state "ShiftLockFirstPerson" as Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLockFirstPerson
    }
    state "ShiftLock" as Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLock
  }
  state "Unlocked" as Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_Unlocked
}

Jomolith_Play_Player_Camera_State_CameraLogic_CameraState --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState : MouseInputOccurred
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState : PhysicsTick
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState : RightClickPressed
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState : RightClickReleased
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState : ZoomedIn
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState : ZoomedOut
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_FirstPerson --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLockFirstPerson : ToggleShiftLock
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_FirstPerson --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_Unlocked : FirstPersonExited
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLock --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLockFirstPerson : FirstPersonEntered
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLock --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_Unlocked : ToggleShiftLock
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLockFirstPerson --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_FirstPerson : ToggleShiftLock
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLockFirstPerson --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLock : FirstPersonExited
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_Unlocked --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_FirstPerson : FirstPersonEntered
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_Unlocked --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLock : ToggleShiftLock

Jomolith_Play_Player_Camera_State_CameraLogic_CameraState : OnMouseInputOccurred → RotationChanged
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState : OnPhysicsTick → GlobalPositionChanged, SpringLengthChanged
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_FirstPerson : OnFirstPersonExited → FirstPersonExited
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_FirstPerson : OnToggleShiftLock → ShiftLockEntered
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLock : OnEnter → OffsetChanged
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLock : OnExit → OffsetChanged
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLock : OnFirstPersonEntered → FirstPersonEntered
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLock : OnToggleShiftLock → ShiftLockExited
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLockFirstPerson : OnFirstPersonExited → FirstPersonExited
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_ShiftLockFirstPerson : OnToggleShiftLock → ShiftLockExited
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_Unlocked : OnFirstPersonEntered → FirstPersonEntered
Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_Unlocked : OnToggleShiftLock → ShiftLockEntered

[*] --> Jomolith_Play_Player_Camera_State_CameraLogic_CameraState_Unlocked
@enduml