@startuml PerspectiveLogic
state "PerspectiveLogic State" as Jomolith_Play_Player_Camera_PerspectiveState_PerspectiveLogic_PerspectiveState {
  state "FirstPerson" as Jomolith_Play_Player_Camera_PerspectiveState_PerspectiveLogic_PerspectiveState_FirstPerson
  state "ThirdPerson" as Jomolith_Play_Player_Camera_PerspectiveState_PerspectiveLogic_PerspectiveState_ThirdPerson
}

Jomolith_Play_Player_Camera_PerspectiveState_PerspectiveLogic_PerspectiveState_FirstPerson --> Jomolith_Play_Player_Camera_PerspectiveState_PerspectiveLogic_PerspectiveState_ThirdPerson : ToThirdPerson
Jomolith_Play_Player_Camera_PerspectiveState_PerspectiveLogic_PerspectiveState_ThirdPerson --> Jomolith_Play_Player_Camera_PerspectiveState_PerspectiveLogic_PerspectiveState_FirstPerson : ToFirstPerson
[*] --> Jomolith_Play_Player_Camera_PerspectiveState_PerspectiveLogic_PerspectiveState_ThirdPerson
@enduml