@startuml TowerLogic
state "TowerLogic State" as Jomolith_Tower_State_TowerLogic_TowerState {
  state "Default" as Jomolith_Tower_State_TowerLogic_TowerState_Default
}

Jomolith_Tower_State_TowerLogic_TowerState_Default --> Jomolith_Tower_State_TowerLogic_TowerState_Default : Default
[*] --> Jomolith_Tower_State_TowerLogic_TowerState_Default
@enduml