@startuml

package JomolithApp-Scene [[../../Src/App/JomolithApp.tscn]] {
    class JomolithApp  {
        [[../../Src/App/JomolithApp.cs ScriptFile]]
        [Nodes]
        Gameplay - [[../../Src/Play/Gameplay/Gameplay.cs Script]]
        MenuScene - [[../../Src/Menu/MenuScene.cs Script]]
        [Properties]
        [[../../Src/App/JomolithApp.cs:30 AppLogic]] - [[../../Src/App/State/AppLogic.Outputs.cs Script]]
        [[../../Src/App/JomolithApp.cs:29 AppRepo]]
        [[../../Src/App/JomolithApp.cs:38 Gameplay]] - [[../../Src/Play/Gameplay/Gameplay.cs Script]]
        [[../../Src/App/JomolithApp.cs:37 GameplayPreview]]
        [[../../Src/App/JomolithApp.cs:36 MenuScene]] - [[../../Src/Menu/MenuScene.cs Script]]
        --
        [Methods]
        [[../../Src/App/JomolithApp.cs:19 _Notification()]]
        [[../../Src/App/JomolithApp.cs:59 OnReady()]]
        [[../../Src/App/JomolithApp.cs:50 OnResolved()]]
        [[../../Src/App/JomolithApp.cs:42 Setup()]]
    }
    package Gameplay-Scene [[../../Src/Play/Gameplay/Gameplay.tscn]] {
        class Gameplay  {
            [[../../Src/Play/Gameplay/Gameplay.cs ScriptFile]]
            [Provisions]
            [[../../Src/Play/Gameplay/Gameplay.cs:34 IGameplayRepo]] - [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs Script]]
            --
            [Interface Properties]
            [[../../Src/Play/Gameplay/Gameplay.cs:43 GameplayLogic]] - [[../../Src/Play/Gameplay/State/GameplayLogic.Outputs.cs Script]]
            [Nodes]
            Player - [[../../Src/Play/Player/Player.cs Script]]
            [Properties]
            [[../../Src/Play/Gameplay/Gameplay.cs:41 GameplayRepo]] - [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs Script]]
            [[../../Src/Play/Gameplay/Gameplay.cs:53 Player]] - [[../../Src/Play/Player/Player.cs Script]]
            [[../../Src/Play/Gameplay/Gameplay.cs:51 Tower]] - [[../../Src/Tower/Tower.cs Script]]
            [[../../Src/Play/Gameplay/Gameplay.cs:45 TowerRepo]]
            --
            [Methods]
            [[../../Src/Play/Gameplay/Gameplay.cs:24 _Notification()]]
            [[../../Src/Play/Gameplay/Gameplay.cs:67 OnResolved()]]
            [[../../Src/Play/Gameplay/Gameplay.cs:86 setPauseMode()]]
            [[../../Src/Play/Gameplay/Gameplay.cs:57 Setup()]]
        }
        package Player-Scene [[../../Src/Play/Player/Player.tscn]] {
            class Player  {
                [[../../Src/Play/Player/Player.cs ScriptFile]]
                [Provisions]
                [[../../Src/Play/Player/Player.cs:20 IPlayerRepo]] - [[../../Src/Play/Player/Domain/PlayerRepo.cs Script]]
                --
                [Nodes]
                Humanoid - [[../../Src/Play/Player/Humanoid/Humanoid.cs Script]]
                PlayerCamera - [[../../Src/Play/Player/Camera/Camera.cs Script]]
                [Properties]
                [[../../Src/Play/Player/Player.cs:32 Humanoid]] - [[../../Src/Play/Player/Humanoid/Humanoid.cs Script]]
                [[../../Src/Play/Player/Player.cs:34 PlayerCamera]] - [[../../Src/Play/Player/Camera/Camera.cs Script]]
                [[../../Src/Play/Player/Player.cs:26 PlayerRepo]] - [[../../Src/Play/Player/Domain/PlayerRepo.cs Script]]
                --
                [Methods]
                [[../../Src/Play/Player/Player.cs:16 _Notification()]]
                [[../../Src/Play/Player/Player.cs:50 OnPhysicsProcess()]]
                [[../../Src/Play/Player/Player.cs:48 OnReady()]]
                [[../../Src/Play/Player/Player.cs:43 OnResolved()]]
                [[../../Src/Play/Player/Player.cs:38 Setup()]]
            }
            package Humanoid-Scene [[../../Src/Play/Player/Humanoid/Humanoid.tscn]] {
                class Humanoid  {
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs ScriptFile]]
                    [Dependencies]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:38 PlayerRepo]] - [[../../Src/Play/Player/Domain/PlayerRepo.cs Script]]
                    [Provisions]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:44 IPlayerLogic]] - [[../../Src/Play/Player/Humanoid/State/PlayerLogic.PlayerSettings.cs Script]]
                    --
                    [Interface Properties]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:78 GlobalRootPosition]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:50 PlayerLogic]] - [[../../Src/Play/Player/Humanoid/State/PlayerLogic.PlayerSettings.cs Script]]
                    [Nodes]
                    PlayerModel - [[../../Src/Play/Player/Humanoid/PlayerModel.cs Script]]
                    [Properties]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:66 ClimbRaycast]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:70 HeadCollisionShape]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:68 HeadRaycast]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:64 LegRaycast]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:79 LocalRootPosition]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:52 PlayerData]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:60 PlayerModel]] - [[../../Src/Play/Player/Humanoid/PlayerModel.cs Script]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:62 RootPart]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:54 Settings]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:72 TorsoCollisionShape]]
                    --
                    [Interface Methods]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:170 GetFloorData()]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:146 GetGlobalInputVector()]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:159 GetNoclipInputVector()]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:253 IsClimbing()]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:131 PhysicsTick()]]
                    [Methods]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:34 _Notification()]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:99 OnResolved()]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:83 Setup()]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:305 updateHeadTransform()]]
                    [[../../Src/Play/Player/Humanoid/Humanoid.cs:310 updateTorsoTransform()]]
                }
                package PlayerModel-Scene [[../../Src/Play/Player/Humanoid/PlayerModel.tscn]] {
                    class PlayerModel  {
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs ScriptFile]]
                        
                        --
                        [Dependencies]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:29 PlayerLogic]] - [[../../Src/Play/Player/Humanoid/State/PlayerLogic.PlayerSettings.cs Script]]
                        --
                        [Nodes]
                        Avatar - [[../../Src/Play/Player/Humanoid/Visuals/Avatar/Avatar.tscn Script]]
                        [Properties]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:52 AnimationStateMachine]]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:51 AnimationTree]]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:54 Head]]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:45 Materials]] - [[../../Src/Play/Player/Humanoid/Utils/PlayerModelMaterials.cs Script]]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:55 Torso]]
                        --
                        [Methods]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:23 _Notification()]]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:111 OnPhysicsProcess()]]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:60 OnReady()]]
                        [[../../Src/Play/Player/Humanoid/PlayerModel.cs:74 OnResolved()]]
                    }
                    class PlayerModelMaterials  {
                        [[../../Src/Play/Player/Humanoid/Utils/PlayerModelMaterials.cs ScriptFile]]
                        [Constructors]
                        [[../../Src/Play/Player/Humanoid/Utils/PlayerModelMaterials.cs:10 PlayerModelMaterials]]([[../../Src/Play/Player/Humanoid/PlayerModel.cs IPlayerModel]] model)
                        --
                        [Methods]
                        [[../../Src/Play/Player/Humanoid/Utils/PlayerModelMaterials.cs:21 duplicateMaterials()]]
                        [[../../Src/Play/Player/Humanoid/Utils/PlayerModelMaterials.cs:15 SetOpacity()]]
                    }
                    PlayerModel::PlayerModelMaterials ---> PlayerModelMaterials
                }
                Humanoid::PlayerModel ---> PlayerModel
            }
            class Camera  {
                [[../../Src/Play/Player/Camera/Camera.cs ScriptFile]]
                [Dependencies]
                [[../../Src/Play/Player/Camera/Camera.cs:41 PlayerRepo]] - [[../../Src/Play/Player/Domain/PlayerRepo.cs Script]]
                [[../../Src/Play/Player/Camera/Camera.cs:43 GameplayRepo]] - [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs Script]]
                --
                [Interface Properties]
                [[../../Src/Play/Player/Camera/Camera.cs:77 CameraDistance]]
                [[../../Src/Play/Player/Camera/Camera.cs:49 CameraLogic]] - [[../../Src/Play/Player/Camera/State/CameraLogic.CameraSettings.cs Script]]
                [[../../Src/Play/Player/Camera/Camera.cs:73 HorizontalRotation]]
                [[../../Src/Play/Player/Camera/Camera.cs:69 OffsetPosition]]
                [[../../Src/Play/Player/Camera/Camera.cs:75 SpringArmLength]]
                [[../../Src/Play/Player/Camera/Camera.cs:71 VerticalRotation]]
                [Properties]
                [[../../Src/Play/Player/Camera/Camera.cs:63 Camera3D]]
                [[../../Src/Play/Player/Camera/Camera.cs:51 CameraData]]
                [[../../Src/Play/Player/Camera/Camera.cs:59 OffsetNode]]
                [[../../Src/Play/Player/Camera/Camera.cs:53 Settings]]
                [[../../Src/Play/Player/Camera/Camera.cs:61 SpringArm3D]]
                --
                [Interface Methods]
                [[../../Src/Play/Player/Camera/Camera.cs:146 PhysicsTick()]]
                [[../../Src/Play/Player/Camera/Camera.cs:151 PostPhysicsTick()]]
                [Methods]
                [[../../Src/Play/Player/Camera/Camera.cs:37 _Notification()]]
                [[../../Src/Play/Player/Camera/Camera.cs:156 _UnhandledInput()]]
                [[../../Src/Play/Player/Camera/Camera.cs:103 OnResolved()]]
                [[../../Src/Play/Player/Camera/Camera.cs:81 Setup()]]
            }
            class PlayerRepo  {
                [[../../Src/Play/Player/Domain/PlayerRepo.cs ScriptFile]]
                [Constructors]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:53 PlayerRepo]]()
                [Interface Properties]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:48 AvatarOpacity]]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:45 CameraBasis]]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:36 IsPlayerRotationLocked]]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:42 PlayerBasis]]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:39 PlayerGlobalPosition]]
                --
                [Interface Methods]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:82 SetAvatarOpacity()]]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:77 SetCameraBasis()]]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:62 SetIsPlayerRotationLocked()]]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:72 SetPlayerBasis()]]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:67 SetPlayerGlobalPosition()]]
                [Methods]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:89 Dispose()]]
                [[../../Src/Play/Player/Domain/PlayerRepo.cs:107 Dispose()]]
            }
            Player::Humanoid ---> Humanoid
            Player::PlayerCamera ---> Camera
            Player::PlayerRepo ---> PlayerRepo
        }
        class GameplayRepo  {
            [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs ScriptFile]]
            [Constructors]
            [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs:45 GameplayRepo]]()
            [Interface Properties]
            [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs:37 IsMouseCaptured]]
            [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs:40 IsPaused]]
            --
            [Interface Methods]
            [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs:56 Pause()]]
            [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs:61 Resume()]]
            [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs:51 SetIsMouseCaptured()]]
            [Methods]
            [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs:68 Dispose()]]
            [[../../Src/Play/Gameplay/Domain/GameplayRepo.cs:83 Dispose()]]
        }
        class Tower  {
            [[../../Src/Tower/Tower.cs ScriptFile]]
            [Properties]
            [[../../Src/Tower/Tower.cs:35 TowerLogic]] - [[../../Src/Tower/State/TowerLogic.Settings.cs Script]]
            --
            [Methods]
            [[../../Src/Tower/Tower.cs:23 _Notification()]]
            [[../../Src/Tower/Tower.cs:48 OnResolved()]]
            [[../../Src/Tower/Tower.cs:41 Setup()]]
        }
        Gameplay::Player ---> Player
        Gameplay::GameplayRepo ---> GameplayRepo
        Gameplay::Tower ---> Tower
    }
    package MenuScene-Scene [[../../Src/Menu/MenuScene.tscn]] {
        class MenuScene  {
            [[../../Src/Menu/MenuScene.cs ScriptFile]]
            [Provisions]
            [[../../Src/Menu/MenuScene.cs:28 IMenuRepo]] - [[../../Src/Menu/Domain/MenuRepo.cs Script]]
            --
            [Nodes]
            TowerSelect - [[../../Src/Menu/Screens/TowerSelect/TowerSelect.cs Script]]
            SettingsMenu - [[../../Src/Menu/Screens/SettingsMenu/SettingsMenu.cs Script]]
            Footer - [[../../Src/Menu/Screens/Components/Footer/Footer.cs Script]]
            MainMenu - [[../../Src/Menu/Screens/MainMenu/MainMenu.cs Script]]
            [Properties]
            [[../../Src/Menu/MenuScene.cs:51 Footer]] - [[../../Src/Menu/Screens/Components/Footer/Footer.cs Script]]
            [[../../Src/Menu/MenuScene.cs:48 MainMenu]] - [[../../Src/Menu/Screens/MainMenu/MainMenu.cs Script]]
            [[../../Src/Menu/MenuScene.cs:41 MenuBinding]]
            [[../../Src/Menu/MenuScene.cs:40 MenuLogic]] - [[../../Src/Menu/State/MenuLogic.Outputs.cs Script]]
            [[../../Src/Menu/MenuScene.cs:42 MenuRepo]] - [[../../Src/Menu/Domain/MenuRepo.cs Script]]
            [[../../Src/Menu/MenuScene.cs:50 SettingsMenu]] - [[../../Src/Menu/Screens/SettingsMenu/SettingsMenu.cs Script]]
            [[../../Src/Menu/MenuScene.cs:49 TowerSelect]] - [[../../Src/Menu/Screens/TowerSelect/TowerSelect.cs Script]]
            --
            [Methods]
            [[../../Src/Menu/MenuScene.cs:24 _Notification()]]
            [[../../Src/Menu/MenuScene.cs:127 BackButtonPressed()]]
            [[../../Src/Menu/MenuScene.cs:123 EditButtonPressed()]]
            [[../../Src/Menu/MenuScene.cs:97 hideAllMenus()]]
            [[../../Src/Menu/MenuScene.cs:113 OnExitTree()]]
            [[../../Src/Menu/MenuScene.cs:64 OnResolved()]]
            [[../../Src/Menu/MenuScene.cs:121 PlayButtonPressed()]]
            [[../../Src/Menu/MenuScene.cs:125 SettingsButtonPressed()]]
            [[../../Src/Menu/MenuScene.cs:55 Setup()]]
            [[../../Src/Menu/MenuScene.cs:105 wireButtons()]]
        }
        class Footer  {
            [[../../Src/Menu/Screens/Components/Footer/Footer.cs ScriptFile]]
            [Properties]
            [[../../Src/Menu/Screens/Components/Footer/Footer.cs:15 BackButton]]
            --
            [Methods]
            [[../../Src/Menu/Screens/Components/Footer/Footer.cs:30 _ExitTree()]]
            [[../../Src/Menu/Screens/Components/Footer/Footer.cs:25 _Ready()]]
            [[../../Src/Menu/Screens/Components/Footer/Footer.cs:35 OnBackButtonPressed()]]
        }
        class MainMenu  {
            [[../../Src/Menu/Screens/MainMenu/MainMenu.cs ScriptFile]]
            [Properties]
            [[../../Src/Menu/Screens/MainMenu/MainMenu.cs:17 EditButton]]
            [[../../Src/Menu/Screens/MainMenu/MainMenu.cs:16 PlayButton]]
            [[../../Src/Menu/Screens/MainMenu/MainMenu.cs:18 SettingsButton]]
            --
            [Methods]
            [[../../Src/Menu/Screens/MainMenu/MainMenu.cs:30 _Ready()]]
            [[../../Src/Menu/Screens/MainMenu/MainMenu.cs:38 OnEditButtonPressed()]]
            [[../../Src/Menu/Screens/MainMenu/MainMenu.cs:37 OnPlayButtonPressed()]]
            [[../../Src/Menu/Screens/MainMenu/MainMenu.cs:39 OnSettingsButtonPressed()]]
        }
        class MenuRepo  {
            [[../../Src/Menu/Domain/MenuRepo.cs ScriptFile]]
            [Constructors]
            [[../../Src/Menu/Domain/MenuRepo.cs:22 MenuRepo]]()
            [Interface Properties]
            [[../../Src/Menu/Domain/MenuRepo.cs:16 CurrentScreen]]
            --
            [Interface Methods]
            [[../../Src/Menu/Domain/MenuRepo.cs:27 SetCurrentScreen()]]
            [Methods]
            [[../../Src/Menu/Domain/MenuRepo.cs:31 Dispose()]]
            [[../../Src/Menu/Domain/MenuRepo.cs:44 Dispose()]]
        }
        MenuScene::Footer ---> Footer
        MenuScene::MainMenu ---> MainMenu
        MenuScene::MenuRepo ---> MenuRepo
    }
    JomolithApp::Gameplay ---> Gameplay
    JomolithApp::MenuScene ---> MenuScene
}

@enduml