@startuml PlayerLogic
state "PlayerLogic State" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState {
  state "Alive" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive {
    state "FallingBase" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_FallingBase {
      state "Coyote" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Coyote
      state "Falling" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Falling
    }
    state "Jumping" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping
    state "RunningBase" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_RunningBase {
      state "Climbing" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Climbing
      state "Idle" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Idle
      state "Landed" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Landed
      state "Running" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Running
    }
  }
  state "Dead" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Dead
  state "Disabled" as Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Disabled
}

Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive : ComputeForces
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive : DesiredMovementVector
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive : PhysicsTick
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive : SetTimer
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Climbing --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping : Jump
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Coyote --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Falling : TimerUp
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Coyote --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping : Jump
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Coyote --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Running : HitFloor
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_FallingBase --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Landed : HitFloor
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Idle --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Climbing : FacingLadder
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Idle --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Coyote : OffFloor
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Idle --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Running : IsMoving
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Falling : ComputeForces
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Falling : OffFloor
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Falling : TimerUp
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping : ComputeForces
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Landed --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Landed : Jump
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Landed --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Running : TimerUp
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Running --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Climbing : FacingLadder
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Running --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Coyote : OffFloor
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Running --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Idle : IsIdle
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_RunningBase --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping : Jump
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_RunningBase --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_RunningBase : OnFloor

Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive : OnComputeForces → ApplyForce
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Alive : OnDesiredMovementVector → ApplyForce, FloorVelocityChanged
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Climbing : OnEnter → Climb
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Falling : OnEnter → Fall
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Idle : OnEnter → Idle
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping : OnComputeForces → ApplyForce
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Jumping : OnEnter → Jump
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Running : OnEnter → Walk
Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_RunningBase : OnOnFloor → ApplyForce

[*] --> Jomolith_Game_Play_Player_State_PlayerLogic_PlayerState_Falling
@enduml